services:
  - type: worker
    name: akhil-tracker-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7635856768:AAGi8Mrkmx2Z6jhnqtENKdM13s_CpMcajT4"
pythonVersion: 3.11.9
